### RNA seq visualization ###


# Prepare for PCA
To create a PCA object I need to remove all rows that have no variance. We can also do a PCA of only the significant genes of one condition, but in this case we do a PCA of the whole set.

```{r}
tpmNormalisedCounts_pca <- tpmNormalisedCounts[rowSums(tpmNormalisedCounts[-1] != tpmNormalisedCounts[[2]], na.rm = TRUE) != 0,]
```


# create PCA object

```{r}

pca <- prcomp(t(tpmNormalisedCounts_pca), center=TRUE, scale=TRUE)
scores <- data.frame(targets$sampleID, pca$x[,1:2])
summary(pca)
```

## create QC plot

```{r}
pointSize <- 0.4
pdf(paste("output/PCA.pdf", sep=""))
ggplot(scores, aes(x = PC1, y = PC2, label=factor(targets$sampleID), colour=factor(targets$Condition) ) ) +
geom_text(size=2.5) + scale_colour_discrete(name="condition")


dev.off()
```

# Heatmap

Plot the tpm values
```{r eval=FALSE, include=FALSE}
library(tibble)
relative_Significant_Genes <- sortedFinalData_named %>% 
  filter(padj <= 0.01) %>%
  filter(log2FoldChange >= 1 | log2FoldChange <= -1) %>%
  dplyr::select(external_gene_name, starts_with("TPM")) %>%
  column_to_rownames(var="external_gene_name") %>%
  data.matrix()

pdf(paste("output/", ConditionTwo, ".pdf"))
heatmap(heatmap_prep)
dev.off()
```

